ummgoban/admin-client-app

- android/app/src/main/AndroidManifest.xml
- ios/AdminClientApp/Info.plist
- package.json
- src/components/common/BottomButton.style.tsx
- src/components/common/Label.style.tsx
- src/components/common/Label.tsx
- src/components/common/TabBar.tsx
- src/components/common/TextInput.style.tsx
- src/components/common/TextInput.tsx
- src/components/common/index.ts
- src/navigation/HomeNavigator.tsx
- src/screens/HomeScreen/index.tsx
- src/screens/MarketInfoScreen/MarketInfoScreen.style.tsx
- src/screens/MarketInfoScreen/index.tsx
- src/types/StackNavigationType.ts
- src/utils/date.ts
- src/utils/image-picker.ts
- yarn.lock
resolves: https://github.com/UOS-Capstone/admin-client-app/issues/4
- install `react-native-date-picker`, `react-native-image-picker`.
- `textInput` 컴포넌트 추가합니다.
- `utils/date` module이 react-native-date-picker와 declare 충돌이 있어서 const date를 export 하는 대신 개별 함수를 export 합니다.
| demo | pick time | upload photo | del photo | save info |
| - | - | - | - | - |
| ![Screenshot_1727509258](https://github.com/user-attachments/assets/521883d8-bec8-4229-b4a2-1cfedfbfeac1) |![Screenshot_1727509505](https://github.com/user-attachments/assets/e60633a6-08c4-4728-9db0-86afb910d8f8) | ![Screenshot_1727509461](https://github.com/user-attachments/assets/80ea2f6e-0e1b-4a4d-9426-77fc77d14c54) | ![Screenshot_1727509263](https://github.com/user-attachments/assets/b39e0a71-5d2d-4e95-83d8-c8f53c74c9c2) | …
> feat: 가게 상세 편집 페이지 제작합니다.

- android/app/build.gradle
- package.json
- src/components/common/TextInput.style.tsx
- src/navigation/RegisterMarketNavigator.tsx
- src/navigation/index.tsx
- src/screens/MyPageScreen/MyPageScreen.style.tsx
- src/screens/MyPageScreen/index.tsx
- src/screens/RegisterMarketScreen/RegisterMarketScreen.style.tsx
- src/screens/RegisterMarketScreen/index.tsx
- src/types/StackNavigationType.ts
- yarn.lock
resolves: #2, #17
- 간단한 마이페이지 구현합니다.
- 매장 추가 버튼 클릭 시 가게 등록 페이지로 이동합니다.
- TODO: 매장 스위칭 기능 개발합니다.
- 입력으로 필수 인자만 받습니다
* 대표자 명
* 개업 일자
* 사업자 등록번호
- TODO: API 연결
| 마이페이지 | invalid | invalid | submit |
|--------|--------|--------|--------|
| ![Screenshot_1728135901](https://github.com/user-attachments/assets/f3ca4f6a-8673-42c9-bb7b-3285707b9b8c) | ![Screenshot_1728135498](https://github.com/user-attachments/assets/34b13e49-382d-4d20-8005-c32a30046fce) | ![Screenshot_1728135507](https://github.com/user-attachments/assets/e100f8fa-5268-4f0d-9200-6e174c0c8b87) |  ![Screenshot_1728135515](https://github.com/user-attachments/assets/1c961a1b-d9c9-4026-ac5e-dcb11b0ef0b5) |
> feat: 마이페이지, 가게 등록 페이지 작성합니다.

- .github/workflows/lint.yml
- package.json
- src/screens/OrderDetailScreen/index.tsx
- github action에서 tsc를 직접호출하는 대신 script에 typecheck 를 추가합니다.
> chore: resolve type check github action

- .github/workflows/lint.yml
- package.json
- src/apis/OrderInfo.ts
- src/components/OrderDetail/Common.style.tsx
- src/components/OrderDetail/OrderCustomerInfo.style.tsx
- src/components/OrderDetail/OrderCustomerInfo.tsx
- src/components/OrderDetail/OrderProductsInfo.style.tsx
- src/components/OrderDetail/OrderProductsInfo.tsx
- src/components/common/TabBar.tsx
- src/navigation/HomeNavigator.tsx
- src/screens/OrderDetailScreen/OrderDetailScreen.style.tsx
- src/screens/OrderDetailScreen/index.tsx
- src/types/OrderDetailType.ts
- src/types/OrderInfoType.ts
- src/types/StackNavigationType.ts
resolves: #8 
```
export type Product = {
id: number;
image: string;
name: string;
originPrice: number;
discountPrice: number;
discountRate: number;
count: number;
};
export type OrderInfoType = {
id: string;
customerRequset: string;
createdAt: string;
pickupReservedAt: string;
ordersPrice: number;
orderMemberName: string;
orderStatus: string;
products: Product[];
};
export type OrderResponseType = {
code: number;
message: string;
data: OrderInfoType[];
};
```
타입 논의 진행 필요합니다.
백엔드와 논의 이후 현재 사용 타입 작성했습니다.
> feat: 주문 상세 페이지 제작

- src/apis/ApiClient.ts
- src/apis/Login.ts
- src/types/Session.ts
> feat: login session 유지

- src/apis/Market.ts
- src/apis/Product.ts
- src/components/common/BottomButton.style.tsx
- src/components/menu/Menu.style.tsx
- src/components/menu/Menu.tsx
- src/components/menu/MenuModal.style.tsx
- src/components/menu/MenuModal.tsx
- src/context/theme.ts
- src/screens/MenuManageScreen/MenuManageDetailScreen.tsx
- src/screens/RegisterMarketScreen/index.tsx
- src/types/ProductType.ts
> fix: 메뉴 변경 페이지 수정, 테마 적용

- ios/Podfile.lock
- package.json
- src/screens/RegisterMarketScreen/RegisterMarketScreen.style.tsx
- src/screens/RegisterMarketScreen/index.tsx
- yarn.lock
- @actbase/react-daum-postcode 통해 도로명주소 연동합니다.
- 검색창은 모달로 구현하였습니다.
- 주소 검색 후 선택시 자동으로 기본주소를 채워줍니다.
- 주소 검색 강제화를 ui적으로 어떻게 개선할까요? 현재는 버튼을 넣어뒀습니다.
- 급한대로 일단 pr 올립니다. 콘솔 경고 해결 / 네비게이션 해결 예정입니다.  기능 확인만 해주세요 
- M2이슈로 ios 빌드시 아마 Pod.lock를 아마 지우고 까셔야 할 것 같네요 ㅠ
- 네비게이션 추가 예정입니다. 사소합니다.
> feat: 도로명 주소 api연동

- src/apis/Market.ts
- src/components/common/TextInput.style.tsx
- src/components/orderDetail/OrderProductsInfo.tsx
- src/screens/MarketInfoScreen/MarketInfoScreen.style.tsx
- src/screens/MarketInfoScreen/index.tsx
- src/screens/MyPageScreen/MyPageScreen.style.tsx
- src/screens/MyPageScreen/index.tsx
- src/screens/RegisterMarketScreen/RegisterMarketScreen.style.tsx
- src/screens/RegisterMarketScreen/index.tsx
- src/screens/RegisterScreen/LoginScreen.tsx
- src/types/Market.ts
resolves: #34
- 디자인은 점진적으로...
- api 등록 성공했어요 
| ![Screenshot_1732030359](https://github.com/user-attachments/assets/518e3fda-16ff-4479-9d5e-e04b04fdb2d9) | ![Screenshot_1732030362](https://github.com/user-attachments/assets/11546877-39ab-44bf-a1f2-46852ec9677b) |
| - | - |
> feat: 매장 등록 플로우 완성

- src/components/common/TabBar.style.tsx
- src/components/common/TabBar.tsx
> feat: 바텀 아이콘 추가합니다.

- src/components/common/TabBar.style.tsx
- src/components/common/TabBar.tsx
- src/components/menu/MenuModal.style.tsx
- src/components/menu/MenuModal.tsx
- src/context/theme.ts
- src/screens/MarketInfoScreen/index.tsx
- src/screens/MenuManageScreen/MenuManageDetailScreen.style.tsx
- src/screens/MenuManageScreen/MenuManageDetailScreen.tsx
- src/screens/MyPageScreen/index.tsx
- src/utils/platform.ts
- 메뉴 추가/수정 모달 컴포넌트가 길어길 경우 스크롤 가능하게 합니다.
- 바텀 탭에 그림자 추가합니다
| 모달 스크롤 | 바텀 탭 그립자 |
| - | - |
| ![Screenshot_1732532102](https://github.com/user-attachments/assets/2a292bed-03b7-4dc0-b780-0d55e8a2d166) | ![Screenshot_1732532023](https://github.com/user-attachments/assets/729bccd4-8a0b-43e9-9e2f-bf4bf6d78d64) |
> feat: 모달 스크롤뷰 추가합니다.

- src/components/common/SwitchContainer.style.tsx
- src/components/common/SwitchContainer.tsx
- src/screens/MarketInfoScreen/index.tsx
- src/screens/MyPageScreen/index.tsx
- src/types/Market.ts
resolves: #50 
- 영업시간, 픽업시간 요일별 설정은 TODO로 남겨두었습니다.
- 영업 임시휴업 설정 TODO로 남겨둡니다.
> fix: 마켓 정보 수정 타임 픽커 한글화, 대표사진 주석, 알림 설정 뷰

- src/apis/Orders.ts
- src/components/pendingOrder/PendingOrder.tsx
- src/screens/OrderHistoryScreen/PendingOrders.tsx
- src/types/OrderDetailType.ts
- 접수된 주문들에 한해 노쇼 버튼 추가하여 픽업완료/노쇼 로 분기 처리합니다
> fix: 주문관리에서 노쇼 처리 버튼 추가

- src/components/common/CustomTextInput.style.tsx
- src/components/menu/MenuModal.style.tsx
- src/components/menu/MenuModal.tsx
- src/components/menu/TagModal.style.tsx
- src/components/menu/TagModal.tsx
- src/context/theme.ts
resolves: #57 
- 태그 모달 디자인 적용했습니다.
- 테마에 pressed 색상 추가했습니다.
| ![Image 1](https://github.com/user-attachments/assets/38483dac-8944-444e-b240-038bae011a30) | ![Image 2](https://github.com/user-attachments/assets/6490aa96-0dd3-45d3-8829-e1282beb17ae) |
|------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
디자인 피드백 주시면 수정하겠습니다.
CustomTextInput width 10px만 키우시면 어떻게 생각하시나요.. @itslitulinchpin2
> fix: 태그 모달 디자인 수정

- src/apis/Orders.ts
- src/components/orderDetail/OrderCustomerInfo.tsx
- src/components/pendingOrder/PendingOrder.style.tsx
- src/components/pendingOrder/PendingOrder.tsx
- src/screens/OrderHistoryScreen/PendingOrders.tsx
- src/types/OrderDetailType.ts
- src/utils/date.ts
> fix: 주문 내역 디자인 고도화

- src/components/orderDetail/OrderCustomerInfo.tsx
- src/components/pendingOrder/PendingOrder.style.tsx
- src/components/pendingOrder/PendingOrder.tsx
- 테마에 맞게 수락/거절/픽업/노쇼 버튼 디자인 수정
- 요청사항은 처리 안하기로 한것 같아서 우선은 주석처리했어요
> fix:주문 관리 버튼 디자인 수정

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
안드로이드 http 통신 허용했습니다.
릴리즈 이후 api 통신 됩니다.
> chore:안드로이드 http 허용

- App.tsx
- package.json
- src/apis/fcm.ts
- src/screens/MyPageScreen/index.tsx
- src/utils/notification.ts
- src/utils/storage.ts
- yarn.lock
- fcm 관리 로직 마이페이지 및 스플래시 스크린으로 이동
권한 관련해서 보완이 필요해보입니다.
차후 진행하겠습니다...
> fix: admin fcm 기능 보완 및 마이페이지로 이동

- android/app/build.gradle
- android/app/src/main/java/com/adminclientapp/MainActivity.kt
- android/app/src/main/java/com/adminclientapp/MainApplication.kt
- package.json
- 안드로이드 패키지 명 com.ummgoban.momchanpickadmin
> chore: android aab build

- src/screens/MenuManageScreen/index.tsx
- src/screens/OrderHistoryScreen/OrderHistoryScreen.style.tsx
- src/screens/OrderHistoryScreen/PendingOrders.tsx
- 주문들 최신순으로 정렬
- 주문 거절시 수량 즉각 반영 위해 메뉴 관리 useIsFocused적용
> fix: 주문 최신순 정렬 / 메뉴관리 useIsFocused 적용

- android/app/build.gradle
- src/apis/ApiClient.ts
> release: 0.0.1

- package.json
- src/apis/markets/client.ts
- src/apis/markets/index.ts
- src/apis/markets/model.ts
- src/apis/markets/query.ts
- src/context/ReactQueryProvider.tsx
- src/context/index.tsx
- src/navigation/HomeNavigator.tsx
- src/screens/MarketInfoScreen/index.tsx
- src/screens/MenuManageScreen/index.tsx
- src/screens/MyPageScreen/index.tsx
- src/screens/OrderHistoryScreen/index.tsx
- src/screens/RegisterMarketScreen/index.tsx
- yarn.lock
- [참조](https://github.com/ummgoban/client-app/pull/143)
> feat: react-query 도입, useMarket 선제반영

- src/apis/managers/client.ts
- src/apis/managers/index.ts
- src/apis/managers/model.ts
- src/apis/managers/query.ts
- src/types/Managers.ts
resolves: #87 
manager role 관련 api fetch function, query 작성합니다.
> feat: 매니저 관련 api 함수, 쿼리 작성

- src/components/LoginPage/CredentialLogin.style.tsx
- src/components/menu/Menu.style.tsx
- src/components/menu/MenuModal.style.tsx
- src/components/menu/TagModal.style.tsx
- src/components/orderDetail/Common.style.tsx
- src/components/orderDetail/OrderCustomerInfo.style.tsx
- src/components/orderDetail/OrderProductsInfo.style.tsx
- src/components/pendingOrder/PendingOrder.style.tsx
- src/components/review/ReviewContainer.style.tsx
- src/components/review/ReviewContainerLists.style.tsx
- src/screens/MarketInfoScreen/MarketInfoScreen.style.tsx
- src/screens/MenuManageScreen/MenuManageDetailScreen.style.tsx
- src/screens/MyPageScreen/MyPageScreen.style.tsx
- src/screens/OrderDetailScreen/OrderDetailScreen.style.tsx
- src/screens/OrderHistoryScreen/OrderHistoryScreen.style.tsx
- src/screens/RegisterMarketScreen/RegisterMarketScreen.style.tsx
- src/screens/RegisterScreen/LoginScreen.style.tsx
- src/screens/ReviewReplyScreen/ReviewReplyScreen.style.tsx
- src/screens/ReviewScreen/ReviewScreen.style.tsx
제시해주신 방법으로 screen.style.tsx 파일 및 feature component 우선 수정합니다.
> fix: 스크린 스타일 파일 컨벤션 수정

- ios/AdminClientApp.xcodeproj/project.pbxproj
- src/apis/managers/query.ts
- src/screens/MarketInfoScreen/index.tsx
> fix: useReadManagers 훅 query key 수정

- src/apis/auth/client.ts
- src/apis/auth/query.ts
- src/components/LoginPage/CredentialSignUp.tsx
- https://github.com/ummgoban/client-app/pull/174 과 동일한 작업
> feat: email send api 수정 및 피드백 추가 

- src/apis/auth/client.ts
- src/hooks/useProfile.ts
- src/screens/MyPageScreen/MyPageScreen.style.tsx
- src/screens/MyPageScreen/index.tsx
> feat: 로그아웃 리프레쉬, 회원탈퇴 버튼 추가

- src/apis/Product.ts
- src/components/LoginPage/CredentialLogin.tsx
- src/components/menu/MenuModal.tsx
- src/hooks/useMarket.ts
- src/hooks/useMemberMarket.ts
- src/hooks/useProfile.ts
- src/screens/MarketInfoScreen/index.tsx
- src/screens/MenuManageScreen/MenuManageDetailScreen.tsx
- src/screens/MyPageScreen/index.tsx
- src/screens/OrderHistoryScreen/index.tsx
- src/screens/RegisterScreen/LoginScreen.tsx
resolves: #98 
- useMemberMarket hook 추가했습니다. 
- useMarket 로직 많이 덜어냈습니다.
뭔가 useMarket 안에서 다 해보려했는데.. 어렵네요.
> fix: 로그인 후 강제 fetch

- src/apis/auth/oauthHelper.ts
> fix: apple-login-request

- src/components/common/NavigationTextButton.tsx
- src/components/common/TabBar.tsx
- src/screens/MenuManageScreen/MenuManageDetailScreen.tsx
- src/screens/MyPageScreen/index.tsx
react native vector icons내 antdesign 버그로 인해 아이콘 교체
탭바 icon 기존구조 유지하기 위해 타입을 확장시켰습니다.
> fix: react-native-vector-icons-antdesign 아이콘 교체

- .github/workflows/lint.yml
- .gitignore
- .npmrc
- .script/ci.sh
- .script/post-install.sh
- .script/pre-install.sh
- .yarnrc.yml.template
- package.json
- src/components/orderDetail/OrderProductsInfo.tsx
- src/types/Market.ts
- src/types/OrderDetailType.ts
- src/types/ProductType.ts
- yarn.lock
> chore: 공통 모듈 패키지 `@ummgoban/shared` 설치 설정합니다.

- android/build.gradle
- yarn.lock
- 안드로이드 빌드 설정 수정합니다.
- feature/image-crop을 베이스로 작업했습니다
> chore: update android sdk

- ios/AdminClientApp.xcodeproj/project.pbxproj
- src/components/manager/ManagerModal.tsx
> release: v1.1.1

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/AdminClientApp.xcodeproj/project.pbxproj
- package.json
- src/apis/auth/client.ts
- src/components/manager/ManagerModal.tsx
- src/hooks/useProfile.ts
- src/screens/MyPageScreen/MyPageScreen.style.tsx
- src/screens/MyPageScreen/index.tsx
- src/screens/RegisterMarketScreen/index.tsx
- src/types/UserType.ts
> release: v1.1.2

- .github/workflows/auto-release.yml
`release: v[x].[y].[z]`형식의 PR이 main으로 머지 시 tag와 release를 생성합니다.
> chore: auto release workflow

- android/app/build.gradle
- package.json
- 지금까지 변경사항 반영한 내용 patch version up 합니다.
> release: v1.1.3

- src/components/manager/ManagerList.tsx
- src/components/manager/ManagerLists.tsx
- src/screens/MarketInfoScreen/MarketInfoScreen.style.tsx
- src/screens/MarketInfoScreen/index.tsx
- src/types/Market.ts
resolves: #129 
- 요일별 영업 시간 분리했습니다.
- 모달 옵션 제거하고 boolean만 채택했습니다
-  기존에 픽업 시간까지 타입 잘 나누셨는데, 픽업시간이 존재하지 않아서 불필요하다 판단되어 삭제했습니다.
> feat: 가게 영업 요일별 시간 분리
